
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=bank_stark
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - bank-network
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - bank-network
    restart: unless-stopped

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mail-dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/bank_stark?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - bank-network
    restart: unless-stopped

networks:
  bank-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
